### ISSUE TITLE
d

### ISSUE THREAD

**Issue by wozzup** [wenerme/cbhistory#1]
d

**Comment by wenerme** [comment]
我记得好像最后那个是随机的

你是打算也做个这样的东西么?我是打算有时间了要从写这个,不知道现在的版本能跑不

**Comment by wozzup** [comment]
我是经常用手机看 cnbeta 受不了他广告太多，哈哈，想自己弄个页面用 js rss 看全文，但是评论有时候有一些也挺好玩的，也想一起看了，哈哈。我测试了一下你现在这个可以用，就是那个 op 的算法我没看明白。。。给解答解答嘛

**Comment by wenerme** [comment]
我不是很记得了,一共就这三个参数,第一个是页数,第二个是一个是 id 吧,第三个好像是随机的
之前版本会把这个给 base64下,好像现在不需要了.

在 2015年3月29日 上午10:46，wozzup notifications@github.com写道：

> 我是经常用手机看 cnbeta 受不了他广告太多，哈哈，想自己弄个页面用 js rss
> 看全文，但是评论有时候有一些也挺好玩的，也想一起看了，哈哈。我测试了一下你现在这个可以用，就是那个 op 的算法我没看明白。。。给解答解答嘛
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wenerme/cbhistory/issues/1#issuecomment-87343426.

## 

Wener~~~~~~~~

**Comment by wozzup** [comment]
rss 里边可以提出他的 page id ，所以，参数就差后面那个随机数了。。。我测试了一个那个随机数真的不是随便随机的，cnbeta 那边好像会验证这个 op 参数

**Comment by wozzup** [comment]
我测试的结果是， op 最后一个参数，可能和日期时间或者客户端ip地址之类的有关系，具体怎么得出 9524c 这样的字符串的也不清楚，可以和我讲讲当初你做这个的时候是怎么算的吗？我来做做试试看。

**Comment by wenerme** [comment]
我记得他会验证你的请求 Header, 要求有个什么字段吧,你可以看下代码

在 2015年3月29日 上午10:52，wozzup notifications@github.com写道：

> rss 里边可以提出他的 page id ，所以，参数就差后面那个随机数了。。。我测试了一个那个随机数真的不是随便随机的，cnbeta
> 那边好像会验证这个 op 参数
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wenerme/cbhistory/issues/1#issuecomment-87343558.

## 

Wener~~~~~~~~

**Comment by wenerme** [comment]
那这个 ID 可能是在 HTML 里的一个 ID, 不是页面 ID, 我哪里有匹配出这个 ID 的正则

在 2015年3月29日 上午11:14，wozzup notifications@github.com写道：

> 我测试的结果是， op 最后一个参数，可能和日期时间或者客户端ip地址之类的有关系，具体怎么得出 9524c
> 这样的字符串的也不清楚，可以和我讲讲当初你做这个的时候是怎么算的吗？我来做做试试看。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wenerme/cbhistory/issues/1#issuecomment-87345539.

## 

Wener~~~~~~~~

**Comment by wozzup** [comment]
对，那个 id 看起来好像是和 url 上的 id 一样的
header 里我看到有一个 ```csrf_token : 53d721f2d4d7f1bb112167f5c73c33c381d32f7e``` 字段

**Comment by wozzup** [comment]
加个 qq 聊嘛：1280844506

**Comment by wenerme** [comment]
等等吧,最近手上的事情忙不过来~
